### ISSUE TITLE
Location tile: add link doesn't function

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-training#3]
On a train records page in the top right of the Locations tile there is the word "add". It seems to be clickable, but when clicked nothing happens.

**Comment by ChrisChasm** [comment]
New locations section is part of the basic details now and uses the same widget as the rest of the system. Should would natively with the location grid default, but it is recommended to get the Mapbox key installed, because this will better track addresses and city locations, as well as unlock high quality maps.
